create table if not exists public.registros (
    id text primary key,
    nombre text not null,
    email text not null,
    telefono text,
    tema_webinar text not null,
    fecha_asistencia date not null,
    resumen text not null,
    quiz_json jsonb not null,
    estado text not null default 'pendiente',
    puntaje numeric,
    constancia_path text,
    created_at timestamptz not null,
    updated_at timestamptz not null
);

create table if not exists public.notificaciones (
    id bigint generated by default as identity primary key,
    registro_id text not null references public.registros(id) on delete cascade,
    canal text not null,
    destino text not null,
    estado text not null,
    detalle text,
    created_at timestamptz not null
);

create index if not exists idx_registros_created_at on public.registros (created_at desc);
create index if not exists idx_notificaciones_registro_id on public.notificaciones (registro_id);

alter table public.registros enable row level security;
alter table public.notificaciones enable row level security;

grant select, insert, update, delete on public.registros to service_role;
grant select, insert, update, delete on public.notificaciones to service_role;
grant usage, select on sequence public.notificaciones_id_seq to service_role;
